### ISSUE TITLE
Port ocamldot to lablgtk3

### ISSUE THREAD

**Issue by XVilka** [zoggy/ocamldot#2]
GTK 2 is being deprecated, and there is largely compatible version of OCaml bindings to GTK 3 is available - [lablgtk3](http://opam.ocaml.org/packages/lablgtk3/).

See lablgtk3 branch here: https://github.com/garrigue/lablgtk/tree/lablgtk3

**Comment by zoggy** [comment]
New release 1.1 now uses lablgtk3. See https://zoggy.frama.io/ocamldot/
